#!/usr/bin/env python3
"""
Generated sequence file
This file is automatically generated from the web interface.
Do not edit manually - changes will be overwritten.
"""

# Sequence execution - commands run directly at module level
try:
    sleep(2)  # Sleep for 2 seconds (not 2000 seconds)
    write_dmx(1, 255)

except Exception as e:
    print(f"Sequence error: {e}")
    raise
