#!/usr/bin/env python3
"""
Generated sequence file
This file is automatically generated from the web interface.
Do not edit manually - changes will be overwritten.
"""

# Sequence execution - commands run directly at module level
try:
    # Test sequence with 2 second sleep
    sleep(2)
    write_dmx(1, 255)
    write_dmx(2, 128)
    sleep(1)
    write_dmx(1, 0)
    write_dmx(2, 0)

except Exception as e:
    print(f"Sequence error: {e}")
    raise
